/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhanvien;


import modified.QLBLModified;
import classes.LayBacLuong;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC
 */
public class KT3Form extends javax.swing.JFrame {
    DefaultTableModel tabelModel ;
  
    List<LayBacLuong> listLayBacLuongs = new ArrayList<>();
    /**
     * Creates new form KT3Form
     */
    public KT3Form()  throws Exception {
        initComponents();
        tabelModel = (DefaultTableModel) jtableBACLUONG.getModel();
        showBACLUONG();
    }
    private void showBACLUONG() throws Exception{
        listLayBacLuongs = QLBLModified.getAllBacLuongsTrongKeToan();
        tabelModel.setRowCount(0);
        for (LayBacLuong lbl : listLayBacLuongs) {
            tabelModel.addRow(new Object[]{
                
                lbl.getManv(),lbl.getTennv(),lbl.getMaphong(),lbl.getPhong(),lbl.getChucvu(),lbl.getMabacluong(),lbl.getBacluong()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Serchbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableBACLUONG = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        manvjtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        fndbtn = new javax.swing.JButton();
        tcjbtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QL Bậc lương");

        Serchbtn.setText("Search");
        Serchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerchbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        jtableBACLUONG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma NV", "Ho Va Ten", "Ma Phong", "Ten Phong", "Ten Chuc Vu", "Ma Bậc Lương ", "Tên Bậc Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtableBACLUONG);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Ma NV");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Ma Bậc Lương");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.1", "1.2", "1.3", "1.4" }));

        fndbtn.setText("FindAll");
        fndbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fndbtnActionPerformed(evt);
            }
        });

        tcjbtn.setText("Trang chu");
        tcjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcjbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manvjtext, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Serchbtn)
                .addGap(65, 65, 65)
                .addComponent(updatebtn)
                .addGap(58, 58, 58)
                .addComponent(resetbtn)
                .addGap(199, 199, 199)
                .addComponent(fndbtn)
                .addGap(18, 18, 18)
                .addComponent(tcjbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manvjtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Serchbtn)
                    .addComponent(updatebtn)
                    .addComponent(resetbtn)
                    .addComponent(fndbtn)
                    .addComponent(tcjbtn))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        
        manvjtext.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void SerchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerchbtnActionPerformed
        // TODO add your handling code here:
        // List<LayBacLuong> nl = new ArrayList<>();
        String manv = manvjtext.getText();
      //  System.out.println(manv.length());
       if(manv.length()>0){
        try {
            listLayBacLuongs = QLBLModified.FindOnBACLUONG(manv);
        } catch (SQLException ex) {
            Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
        }
           
//
       tabelModel.setRowCount(0);
      for (LayBacLuong lbl: listLayBacLuongs) {
            tabelModel.addRow(new Object[]{
                lbl.getManv(),lbl.getTennv(),lbl.getMaphong(),lbl.getPhong(),lbl.getChucvu(),lbl.getMabacluong(),lbl.getBacluong()
             });
           // System.out.println("1");
            }
        }
    }//GEN-LAST:event_SerchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String manv = manvjtext.getText();
        double bacluong = Double.parseDouble( String.valueOf( jComboBox1.getSelectedItem()));
       // System.out.println(bacluong);
       
        String mabacluong = null;
        try {
            mabacluong = QLBLModified.getMaBac(bacluong);
            //System.out.println(mabacluong);
        } catch (SQLException ex) {
            Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
       try {
            QLBLModified.changeBacLuong(manv, mabacluong,bacluong);
        } catch (SQLException ex) {
            Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
       
        try {
            listLayBacLuongs = QLBLModified.FindOnBACLUONG(manv);
        } catch (SQLException ex) {
            Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        

        tabelModel.setRowCount(0);
        for (LayBacLuong lbl : listLayBacLuongs) {
            tabelModel.addRow(new Object[]{
                lbl.getManv(),lbl.getTennv(),lbl.getMaphong(),lbl.getPhong(),lbl.getChucvu(),lbl.getMabacluong(),lbl.getBacluong()
             });
            }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void fndbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fndbtnActionPerformed
        try {
            // TODO add your handling code here:
            listLayBacLuongs = QLBLModified.getAllBacLuongsTrongKeToan();
        } catch (SQLException ex) {
            Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabelModel.setRowCount(0);
        for (LayBacLuong lbl : listLayBacLuongs) {
            tabelModel.addRow(new Object[]{
                
                lbl.getManv(),lbl.getTennv(),lbl.getMaphong(),lbl.getPhong(),lbl.getChucvu(),lbl.getMabacluong(),lbl.getBacluong()
            });
        }
    }//GEN-LAST:event_fndbtnActionPerformed

    private void tcjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcjbtnActionPerformed
        // TODO add your handling code here:
       kt1Form st = null;
        try {
            st = new kt1Form();
        } catch (Exception ex) {
            Logger.getLogger(kt1Form.class.getName()).log(Level.SEVERE, null, ex);
        }
                st.show();
                this.dispose();
    }//GEN-LAST:event_tcjbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KT3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KT3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KT3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KT3Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KT3Form().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Serchbtn;
    private javax.swing.JButton fndbtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtableBACLUONG;
    private javax.swing.JTextField manvjtext;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton tcjbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
