/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhanvien;

import modified.LUONGModified;
import classes.LayLuong;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QLHSLFORM extends javax.swing.JFrame {
    DefaultTableModel tabelModel ;
  
    List<LayLuong> listLayLuongs = new ArrayList<>();
    /**
     * Creates new form QLHSLFORM
     */
    public QLHSLFORM() throws Exception {
        initComponents();
        tabelModel = (DefaultTableModel) jtabelLuong.getModel();
        showlUONG();
    }
    private void showlUONG() throws Exception{
        listLayLuongs = LUONGModified.getAll();
        tabelModel.setRowCount(0);
        for (LayLuong lbl : listLayLuongs) {
            tabelModel.addRow(new Object[]{
                
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getChucvu(),lbl.getLuong()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manvfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        findallbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelLuong = new javax.swing.JTable();
        tcbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("LƯƠNG NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Ma NV");

        searchbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        findallbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        findallbtn.setText("FindAll");
        findallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findallbtnActionPerformed(evt);
            }
        });

        jtabelLuong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtabelLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "Ten NV", "Phong", "Chuc vu", "Luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtabelLuong);
        if (jtabelLuong.getColumnModel().getColumnCount() > 0) {
            jtabelLuong.getColumnModel().getColumn(4).setResizable(false);
        }

        tcbtn.setText("Trang chu");
        tcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manvfield)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchbtn)
                                .addGap(55, 55, 55)
                                .addComponent(findallbtn)
                                .addGap(0, 131, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(tcbtn)
                        .addGap(4, 4, 4))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manvfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn)
                    .addComponent(findallbtn)
                    .addComponent(tcbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findallbtnActionPerformed
        try {
            // TODO add your handling code here:
            listLayLuongs = LUONGModified.getAll();
        } catch (Exception ex) {
            Logger.getLogger(QLHSLFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabelModel.setRowCount(0);
        for (LayLuong lbl : listLayLuongs) {
            tabelModel.addRow(new Object[]{
                
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getChucvu(),lbl.getLuong()
            });
        }
    }//GEN-LAST:event_findallbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String manv =manvfield.getText();
         if(manv.length()>0){
        try {
            listLayLuongs = LUONGModified.FindLUONG(manv);
        } catch (SQLException ex) {
            Logger.getLogger(KT3Form.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (Exception ex) {
                Logger.getLogger(QLHSLFORM.class.getName()).log(Level.SEVERE, null, ex);
            }
           
//
       tabelModel.setRowCount(0);
      for (LayLuong lbl: listLayLuongs) {
            tabelModel.addRow(new Object[]{
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getChucvu(),lbl.getLuong()
             });
           // System.out.println("1");
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void tcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcbtnActionPerformed
        // TODO add your handling code here:
        kt1Form st = null;
        try {
            st = new kt1Form();
        } catch (Exception ex) {
            Logger.getLogger(kt1Form.class.getName()).log(Level.SEVERE, null, ex);
        }
                st.show();
                this.dispose();
    }//GEN-LAST:event_tcbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHSLFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHSLFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHSLFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHSLFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLHSLFORM().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(QLHSLFORM.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findallbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabelLuong;
    private javax.swing.JTextField manvfield;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton tcbtn;
    // End of variables declaration//GEN-END:variables

    private void showLUONG() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
