/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhanvien;

import classes.LayPhuCap;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modified.PhuCap;

/**
 *
 * @author PC
 */
public class QLPCForm extends javax.swing.JFrame {
     DefaultTableModel tabelModel ;
  
    List<LayPhuCap> listLayPhuCaps = new ArrayList<>();

    /**
     * Creates new form QLPCForm
     */
    public QLPCForm() throws Exception {
        initComponents();
        tabelModel = (DefaultTableModel) jTable1.getModel();
        showPHUCAP();
    }
    private void showPHUCAP() throws Exception{
        listLayPhuCaps = PhuCap.getAllPhuCapTrongKeToan();
        tabelModel.setRowCount(0);
        for (LayPhuCap lbl : listLayPhuCaps) {
            tabelModel.addRow(new Object[]{
                
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getNgachluong(),lbl.getBacluong(),lbl.getPhucap()
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manvjtext = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        searchbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        findallbtn = new javax.swing.JButton();
        trangchubtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("QL PHỤ CẤP");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Ma NV");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Phụ Cấp");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000000", "3000000" }));

        searchbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        resetbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        findallbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        findallbtn.setText("Find All");
        findallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findallbtnActionPerformed(evt);
            }
        });

        trangchubtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        trangchubtn.setText("Trang chu");
        trangchubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangchubtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma NV", "Ten NV", "Phong", "Ngach Luong", "Bac Luong", "Phu Cap"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manvjtext)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchbtn)
                        .addGap(18, 18, 18)
                        .addComponent(resetbtn)
                        .addGap(31, 31, 31)
                        .addComponent(updatebtn)
                        .addGap(36, 36, 36)
                        .addComponent(findallbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(trangchubtn)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manvjtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn)
                    .addComponent(resetbtn)
                    .addComponent(updatebtn)
                    .addComponent(findallbtn)
                    .addComponent(trangchubtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        manvjtext.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
          String manv = manvjtext.getText();
      //  System.out.println(manv.length());
       if(manv.length()>0){
        
              try {
                  listLayPhuCaps = PhuCap.getPHUCAP(manv);
              } catch (SQLException ex) {
                  Logger.getLogger(QLPCForm.class.getName()).log(Level.SEVERE, null, ex);
              }
        
//
       tabelModel.setRowCount(0);
      for (LayPhuCap lbl: listLayPhuCaps) {
            tabelModel.addRow(new Object[]{
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getNgachluong(),lbl.getBacluong(),lbl.getPhucap()
             });
           // System.out.println("1");
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void findallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findallbtnActionPerformed
         try {
             // TODO add your handling code here:
             
             // TODO add your handling code here:
             listLayPhuCaps = PhuCap.getAllPhuCapTrongKeToan();
         } catch (SQLException ex) {
             Logger.getLogger(QLPCForm.class.getName()).log(Level.SEVERE, null, ex);
         }
       
        tabelModel.setRowCount(0);
        for (LayPhuCap lbl : listLayPhuCaps) {
            tabelModel.addRow(new Object[]{
                
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getNgachluong(),lbl.getBacluong(),lbl.getPhucap()
            });
        }
    }//GEN-LAST:event_findallbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
         String manv = manvjtext.getText();
        double phucap = Double.parseDouble( String.valueOf( jComboBox1.getSelectedItem()));
       // System.out.println(bacluong);
       //phucap
         try {
             PhuCap.changePhuCap(manv,phucap);
         } catch (SQLException ex) {
             Logger.getLogger(QLPCForm.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
             listLayPhuCaps = PhuCap.getPHUCAP(manv);
         } catch (SQLException ex) {
             Logger.getLogger(QLPCForm.class.getName()).log(Level.SEVERE, null, ex);
         }
        tabelModel.setRowCount(0);
        for (LayPhuCap lbl : listLayPhuCaps) {
            tabelModel.addRow(new Object[]{
                lbl.getManv(),lbl.getTennv(),lbl.getPhong(),lbl.getNgachluong(),lbl.getBacluong(),lbl.getPhucap()
             });
            }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void trangchubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangchubtnActionPerformed
        // TODO add your handling code here:
          kt1Form st = null;
        try {
            st = new kt1Form();
        } catch (Exception ex) {
            Logger.getLogger(kt1Form.class.getName()).log(Level.SEVERE, null, ex);
        }
                st.show();
                this.dispose();
    }//GEN-LAST:event_trangchubtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLPCForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(QLPCForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findallbtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField manvjtext;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton trangchubtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
